//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrozzleApplication {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConfigurationKeys {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConfigurationKeys() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrozzleApplication.ConfigurationKeys", typeof(ConfigurationKeys).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 BGCOLOUR-EMPTY-TD 的本地化字符串。
        /// </summary>
        internal static string BGCOLOUR_EMPTY_TD {
            get {
                return ResourceManager.GetString("BGCOLOUR_EMPTY_TD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BGCOLOUR-NON-EMPTY-TD 的本地化字符串。
        /// </summary>
        internal static string BGCOLOUR_NON_EMPTY_TD {
            get {
                return ResourceManager.GetString("BGCOLOUR_NON_EMPTY_TD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CROZZLE-OUTPUT 的本地化字符串。
        /// </summary>
        internal static string CROZZLE_OUTPUT {
            get {
                return ResourceManager.GetString("CROZZLE_OUTPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CROZZLE-SIZE 的本地化字符串。
        /// </summary>
        internal static string CROZZLE_SIZE {
            get {
                return ResourceManager.GetString("CROZZLE_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DUPLICATE-SEQUENCES 的本地化字符串。
        /// </summary>
        internal static string DUPLICATE_SEQUENCES {
            get {
                return ResourceManager.GetString("DUPLICATE_SEQUENCES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 END-CROZZLE-OUTPUT 的本地化字符串。
        /// </summary>
        internal static string END_CROZZLE_OUTPUT {
            get {
                return ResourceManager.GetString("END_CROZZLE_OUTPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 END-CROZZLE-SIZE 的本地化字符串。
        /// </summary>
        internal static string END_CROZZLE_SIZE {
            get {
                return ResourceManager.GetString("END_CROZZLE_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 END-DUPLICATE-SEQUENCES 的本地化字符串。
        /// </summary>
        internal static string END_DUPLICATE_SEQUENCES {
            get {
                return ResourceManager.GetString("END_DUPLICATE_SEQUENCES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 END-INTERSECTING-POINTS 的本地化字符串。
        /// </summary>
        internal static string END_INTERSECTION_POINTS {
            get {
                return ResourceManager.GetString("END_INTERSECTION_POINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 END-INTERSECTIONS-IN-SEQUENCES 的本地化字符串。
        /// </summary>
        internal static string END_INTERSECTIONS_IN_SEQUENCES {
            get {
                return ResourceManager.GetString("END_INTERSECTIONS_IN_SEQUENCES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 END-LOGFILE 的本地化字符串。
        /// </summary>
        internal static string END_LOGFILE {
            get {
                return ResourceManager.GetString("END_LOGFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 END-NON-INTERSECTING-POINTS 的本地化字符串。
        /// </summary>
        internal static string END_NON_INTERSECTING_POINTS {
            get {
                return ResourceManager.GetString("END_NON_INTERSECTING_POINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 END-SEQUENCES-IN-CROZZLE 的本地化字符串。
        /// </summary>
        internal static string END_SEQUENCES_IN_CROZZLE {
            get {
                return ResourceManager.GetString("END_SEQUENCES_IN_CROZZLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 END-SEQUENCES-IN-FILE 的本地化字符串。
        /// </summary>
        internal static string END_SEQUENCES_IN_FILE {
            get {
                return ResourceManager.GetString("END_SEQUENCES_IN_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 END-VALID-GROUPS 的本地化字符串。
        /// </summary>
        internal static string END_VALID_GROUPS {
            get {
                return ResourceManager.GetString("END_VALID_GROUPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 INTERSECTING-POINTS 的本地化字符串。
        /// </summary>
        internal static string INTERSECTING_POINTS {
            get {
                return ResourceManager.GetString("INTERSECTING_POINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 INTERSECTIONS-IN-SEQUENCES 的本地化字符串。
        /// </summary>
        internal static string INTERSECTIONS_IN_SEQUENCES {
            get {
                return ResourceManager.GetString("INTERSECTIONS_IN_SEQUENCES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 INVALID-CROZZLE-SCORE 的本地化字符串。
        /// </summary>
        internal static string INVALID_CROZZLE_SCORE {
            get {
                return ResourceManager.GetString("INVALID_CROZZLE_SCORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LOGFILE 的本地化字符串。
        /// </summary>
        internal static string LOGFILE {
            get {
                return ResourceManager.GetString("LOGFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DEFAULT 的本地化字符串。
        /// </summary>
        internal static string LOGFILE_NAME {
            get {
                return ResourceManager.GetString("LOGFILE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MAXIMUM-HORIZONTAL 的本地化字符串。
        /// </summary>
        internal static string MAXIMUM_HORIZONTAL_WORDS {
            get {
                return ResourceManager.GetString("MAXIMUM_HORIZONTAL_WORDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MAXIMUM-HORIZONTAL 的本地化字符串。
        /// </summary>
        internal static string MAXIMUM_INTERSECTIONS_IN_HORIZONTAL_WORDS {
            get {
                return ResourceManager.GetString("MAXIMUM_INTERSECTIONS_IN_HORIZONTAL_WORDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MAXIMUM-VERTICAL 的本地化字符串。
        /// </summary>
        internal static string MAXIMUM_INTERSECTIONS_IN_VERTICAL_WORDS {
            get {
                return ResourceManager.GetString("MAXIMUM_INTERSECTIONS_IN_VERTICAL_WORDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MAXIMUM-COLUMNS 的本地化字符串。
        /// </summary>
        internal static string MAXIMUM_NUMBER_OF_COLUMNS {
            get {
                return ResourceManager.GetString("MAXIMUM_NUMBER_OF_COLUMNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MAXIMUM 的本地化字符串。
        /// </summary>
        internal static string MAXIMUM_NUMBER_OF_GROUPS {
            get {
                return ResourceManager.GetString("MAXIMUM_NUMBER_OF_GROUPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MAXIMUM-ROWS 的本地化字符串。
        /// </summary>
        internal static string MAXIMUM_NUMBER_OF_ROWS {
            get {
                return ResourceManager.GetString("MAXIMUM_NUMBER_OF_ROWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MAXIMUM 的本地化字符串。
        /// </summary>
        internal static string MAXIMUM_NUMBER_OF_THE_SAME_WORD {
            get {
                return ResourceManager.GetString("MAXIMUM_NUMBER_OF_THE_SAME_WORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MAXIMUM 的本地化字符串。
        /// </summary>
        internal static string MAXIMUM_NUMBER_OF_UNIQUE_WORDS {
            get {
                return ResourceManager.GetString("MAXIMUM_NUMBER_OF_UNIQUE_WORDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MAXIMUM-VERTICAL 的本地化字符串。
        /// </summary>
        internal static string MAXIMUM_VERTICAL_WORDS {
            get {
                return ResourceManager.GetString("MAXIMUM_VERTICAL_WORDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MINIMUM-HORIZONTAL 的本地化字符串。
        /// </summary>
        internal static string MINIMUM_HORIZONTAL_WORDS {
            get {
                return ResourceManager.GetString("MINIMUM_HORIZONTAL_WORDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MINIMUM-HORIZONTAL 的本地化字符串。
        /// </summary>
        internal static string MINIMUM_INTERSECTIONS_IN_HORIZONTAL_WORDS {
            get {
                return ResourceManager.GetString("MINIMUM_INTERSECTIONS_IN_HORIZONTAL_WORDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MINIMUM-VERTICAL 的本地化字符串。
        /// </summary>
        internal static string MINIMUM_INTERSECTIONS_IN_VERTICAL_WORDS {
            get {
                return ResourceManager.GetString("MINIMUM_INTERSECTIONS_IN_VERTICAL_WORDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MINIMUM-COLUMNS 的本地化字符串。
        /// </summary>
        internal static string MINIMUM_NUMBER_OF_COLUMNS {
            get {
                return ResourceManager.GetString("MINIMUM_NUMBER_OF_COLUMNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MINIMUM 的本地化字符串。
        /// </summary>
        internal static string MINIMUM_NUMBER_OF_GROUPS {
            get {
                return ResourceManager.GetString("MINIMUM_NUMBER_OF_GROUPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MINIMUM-ROWS 的本地化字符串。
        /// </summary>
        internal static string MINIMUM_NUMBER_OF_ROWS {
            get {
                return ResourceManager.GetString("MINIMUM_NUMBER_OF_ROWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MINIMUM 的本地化字符串。
        /// </summary>
        internal static string MINIMUM_NUMBER_OF_THE_SAME_WORD {
            get {
                return ResourceManager.GetString("MINIMUM_NUMBER_OF_THE_SAME_WORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MINIMUM 的本地化字符串。
        /// </summary>
        internal static string MINIMUM_NUMBER_OF_UNIQUE_WORDS {
            get {
                return ResourceManager.GetString("MINIMUM_NUMBER_OF_UNIQUE_WORDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MINIMUM-VERTICAL 的本地化字符串。
        /// </summary>
        internal static string MINIMUM_VERTICAL_WORDS {
            get {
                return ResourceManager.GetString("MINIMUM_VERTICAL_WORDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NO-CONFIGURATION-ITEM 的本地化字符串。
        /// </summary>
        internal static string NO_CONFIGURATION_ITEM {
            get {
                return ResourceManager.GetString("NO_CONFIGURATION_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NON-INTERSECTING-POINTS 的本地化字符串。
        /// </summary>
        internal static string NON_INTERSECTING_POINTS {
            get {
                return ResourceManager.GetString("NON_INTERSECTING_POINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 POINTS_PER_WORD 的本地化字符串。
        /// </summary>
        internal static string POINTS_PER_WORD {
            get {
                return ResourceManager.GetString("POINTS_PER_WORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SEQUENCES-IN-CROZZLE 的本地化字符串。
        /// </summary>
        internal static string SEQUENCES_IN_CROZZLE {
            get {
                return ResourceManager.GetString("SEQUENCES_IN_CROZZLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SEQUENCES-IN-FILE 的本地化字符串。
        /// </summary>
        internal static string SEQUENCES_IN_FILE {
            get {
                return ResourceManager.GetString("SEQUENCES_IN_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 STYLE 的本地化字符串。
        /// </summary>
        internal static string STYLE {
            get {
                return ResourceManager.GetString("STYLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UPPERCASE 的本地化字符串。
        /// </summary>
        internal static string UPPERCASE {
            get {
                return ResourceManager.GetString("UPPERCASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VALID-GROUPS 的本地化字符串。
        /// </summary>
        internal static string VALID_GROUPS {
            get {
                return ResourceManager.GetString("VALID_GROUPS", resourceCulture);
            }
        }
    }
}
