//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrozzleApplication {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CrozzleErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CrozzleErrors() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrozzleApplication.CrozzleErrors", typeof(CrozzleErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 code 11005: the number of groups of connected words is {0}, but this is not within [{1}, {2}] 的本地化字符串。
        /// </summary>
        internal static string ConnectivityError {
            get {
                return ResourceManager.GetString("ConnectivityError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 code 11003: the number of times {0} occurs is {1}, but this is not within [{2}, {3}] 的本地化字符串。
        /// </summary>
        internal static string DuplicateWordCountError {
            get {
                return ResourceManager.GetString("DuplicateWordCountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 code 11002: the number of horizontal words intersecting {0} is {1}, but this is not within [{2}, {3}] 的本地化字符串。
        /// </summary>
        internal static string HorizontalIntersectionsError {
            get {
                return ResourceManager.GetString("HorizontalIntersectionsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 code 11007: the number of horizontal words is {0}, but this is not within [{1}, {2}] 的本地化字符串。
        /// </summary>
        internal static string HorizontalWordCountError {
            get {
                return ResourceManager.GetString("HorizontalWordCountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 code 11009: the horizontal word ({0}) doesn&apos;t fit into grid 的本地化字符串。
        /// </summary>
        internal static string HorizontalWordSizeError {
            get {
                return ResourceManager.GetString("HorizontalWordSizeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 code 11011: {0} at ({1}, {2}) is not in the word list 的本地化字符串。
        /// </summary>
        internal static string MissingFromWordlistError {
            get {
                return ResourceManager.GetString("MissingFromWordlistError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 code 11001: the number of vertical words intersecting {0} is {1}, but this is not within [{2}, {3}] 的本地化字符串。
        /// </summary>
        internal static string VerticalIntersectionsError {
            get {
                return ResourceManager.GetString("VerticalIntersectionsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 code 11008: the number of vertical words is {0} but this is not within [{1}, {2}] 的本地化字符串。
        /// </summary>
        internal static string VerticalWordCountError {
            get {
                return ResourceManager.GetString("VerticalWordCountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 code 11010: the vertical word ({0}) doesn&apos;t fit into grid 的本地化字符串。
        /// </summary>
        internal static string VerticalWordSizeError {
            get {
                return ResourceManager.GetString("VerticalWordSizeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 code 11006: the number of words is {0}, but this is not within ({1}, {2}) 的本地化字符串。
        /// </summary>
        internal static string WordCountError {
            get {
                return ResourceManager.GetString("WordCountError", resourceCulture);
            }
        }
    }
}
