//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrozzleApplication {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CrozzleKeys {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CrozzleKeys() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrozzleApplication.CrozzleKeys", typeof(CrozzleKeys).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 CONFIG-DATA 的本地化字符串。
        /// </summary>
        internal static string ConfigData {
            get {
                return ResourceManager.GetString("ConfigData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CROZZLE-SIZE 的本地化字符串。
        /// </summary>
        internal static string CrozzleSize {
            get {
                return ResourceManager.GetString("CrozzleSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 END-CROZZLE-SIZE 的本地化字符串。
        /// </summary>
        internal static string EndCrozzleSize {
            get {
                return ResourceManager.GetString("EndCrozzleSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 END-FILE-DEPENDENCIES 的本地化字符串。
        /// </summary>
        internal static string EndFileDependencies {
            get {
                return ResourceManager.GetString("EndFileDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 END-HORIZONTAL-SEQUENCES 的本地化字符串。
        /// </summary>
        internal static string EndHorizontalSequence {
            get {
                return ResourceManager.GetString("EndHorizontalSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 END-VERTICAL-SEQUENCES 的本地化字符串。
        /// </summary>
        internal static string EndVerticalSequence {
            get {
                return ResourceManager.GetString("EndVerticalSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FILE-DEPENDENCIES 的本地化字符串。
        /// </summary>
        internal static string FileDependencies {
            get {
                return ResourceManager.GetString("FileDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LOCATION 的本地化字符串。
        /// </summary>
        internal static string HLocation {
            get {
                return ResourceManager.GetString("HLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HORIZONTAL-SEQUENCES 的本地化字符串。
        /// </summary>
        internal static string HorizontalSequence {
            get {
                return ResourceManager.GetString("HorizontalSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SEQUENCE 的本地化字符串。
        /// </summary>
        internal static string HSequence {
            get {
                return ResourceManager.GetString("HSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NO-CROZZLE-ITEM 的本地化字符串。
        /// </summary>
        internal static string NoCrozzleItem {
            get {
                return ResourceManager.GetString("NoCrozzleItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SEQUENCE-DATA 的本地化字符串。
        /// </summary>
        internal static string SequenceData {
            get {
                return ResourceManager.GetString("SequenceData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SIZE 的本地化字符串。
        /// </summary>
        internal static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VERTICAL-SEQUENCES 的本地化字符串。
        /// </summary>
        internal static string VerticalSequence {
            get {
                return ResourceManager.GetString("VerticalSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LOCATION 的本地化字符串。
        /// </summary>
        internal static string VLocation {
            get {
                return ResourceManager.GetString("VLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SEQUENCE 的本地化字符串。
        /// </summary>
        internal static string VSequence {
            get {
                return ResourceManager.GetString("VSequence", resourceCulture);
            }
        }
    }
}
