//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrozzleApplication {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WordListErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WordListErrors() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrozzleApplication.WordListErrors", typeof(WordListErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 code 10001: non-alphabetic value ({0}) in field ({1}) of the wordlist 的本地化字符串。
        /// </summary>
        internal static string AlphabeticError {
            get {
                return ResourceManager.GetString("AlphabeticError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 code 10013: sequence ({0}) is duplicated 的本地化字符串。
        /// </summary>
        internal static string DuplicateError {
            get {
                return ResourceManager.GetString("DuplicateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 code 10012: word ({0}) is invalid in field ({1}) of the wordlist 的本地化字符串。
        /// </summary>
        internal static string InvalidWordError {
            get {
                return ResourceManager.GetString("InvalidWordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 code 10004: the wordlist size ({0}) is more than the expected maximum ({1}) 的本地化字符串。
        /// </summary>
        internal static string MaximumSizeError {
            get {
                return ResourceManager.GetString("MaximumSizeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 code 10003: the wordlist size ({0}) is less than the expected minimum ({1}) 的本地化字符串。
        /// </summary>
        internal static string MinimumSizeError {
            get {
                return ResourceManager.GetString("MinimumSizeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 code 10002: missing word in field ({0}) of the wordlist 的本地化字符串。
        /// </summary>
        internal static string MissingWordError {
            get {
                return ResourceManager.GetString("MissingWordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 code 10011: the total ASCII ({0}) of all wordlist does not match the pre-defined total ASCII {1} 的本地化字符串。
        /// </summary>
        internal static string TotalASCIIError {
            get {
                return ResourceManager.GetString("TotalASCIIError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 code 10009: the total hash ({0}) of all wordlist does not match the pre-defined total hash {1} 的本地化字符串。
        /// </summary>
        internal static string TotalHashError {
            get {
                return ResourceManager.GetString("TotalHashError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 code 10008: the total length ({0}) of all wordlist does not match the pre-defined total length {1}  的本地化字符串。
        /// </summary>
        internal static string TotalLengthError {
            get {
                return ResourceManager.GetString("TotalLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 code 10010: the total score({0}) of all wordlist does not match the pre-defined total score {1} 的本地化字符串。
        /// </summary>
        internal static string TotalScoreError {
            get {
                return ResourceManager.GetString("TotalScoreError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 code 10005: the ASCII value of word &quot;({0})&quot; does not match the pre-defined ASCII value {1} 的本地化字符串。
        /// </summary>
        internal static string WordASCIIError {
            get {
                return ResourceManager.GetString("WordASCIIError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 code 10006: the Hash value in field &quot;({0})&quot; does not match the pre-defined Hash value {1} 的本地化字符串。
        /// </summary>
        internal static string WordHashError {
            get {
                return ResourceManager.GetString("WordHashError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 code 10007: the length of word &quot;({0})&quot; does not match the pre-defined length {1} 的本地化字符串。
        /// </summary>
        internal static string WordLengthError {
            get {
                return ResourceManager.GetString("WordLengthError", resourceCulture);
            }
        }
    }
}
